version: "3.9"

services:
  gateway-service:
    image: gateway-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    container_name: gateway-service
    build: ./gateway-service
    depends_on:
      - discovery-service
      - authentication-service
      - goods-service
      - order-service
      - history-service
      - attachment-service
      - payment-service
      - comment-service
      - feedback-service
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    deploy:
      resources:
        limits:
         memory: 512M
        reservations:
          memory: 256M

  discovery-service:
    image: quay.io/ibm_cloud_academy/springboot-eureka-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  authentication-service:
    image: authentication-service
    restart: unless-stopped
    ports:
      - "8089:8089"
    container_name: authentication-service
    build: ./authentication-service
    depends_on:
      - authdb
      - discovery-service
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://authdb:5432/auth
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    command: >
      liquibase --url=jdbc:postgresql://authdb:5432/auth --username=test --password=test --driver=org.postgresql.Driver --changeLogFile=classpath:db/changelog/db-changelog-master.yaml --requireForce=true dropAll
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  authdb:
    image: debezium/postgres:15-alpine
    container_name: authDb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=auth
    ports:
      - "5432:5432"
    depends_on:
      - zookeeper
      - kafka
      - kafdrop
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  goods-service:
    image: goods-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    container_name: goods-service
    build: ./goods-service
    depends_on:
      - goodsdb
      - authentication-service
      - discovery-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://goodsdb:5432/goods
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    command: >
      liquibase --url=jdbc:postgresql://goodsdb:5432/goods --username=test --password=test --driver=org.postgresql.Driver --changeLogFile=classpath:db/changelog/db-changelog-master.yaml --requireForce=true dropAll
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  goodsdb:
    image: debezium/postgres:15-alpine
    container_name: goodsDb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=goods
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  order-service:
    image: order-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    container_name: order-service
    build: ./order-service
    depends_on:
      - orderdb
      - discovery-service
      - authentication-service
      - goods-service
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orderdb:5432/orders
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    command: >
      liquibase --url=jdbc:postgresql://orderdb:5432/orders --username=test --password=test --driver=org.postgresql.Driver --changeLogFile=classpath:db/changelog/db-changelog-master.yaml --requireForce=true dropAll
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  orderdb:
    image: debezium/postgres:15-alpine
    container_name: orderDb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=orders
    ports:
      - "5434:5432"
    depends_on:
      - zookeeper
      - kafka
      - kafdrop
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  history-service:
    image: history-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    container_name: history-service
    build: ./history-service
    depends_on:
      - historydb
      - discovery-service
      - authentication-service
      - goods-service
      - order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://historydb:5432/history
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    command: >
      liquibase --url=jdbc:postgresql://historydb:5432/history --username=test --password=test --driver=org.postgresql.Driver --changeLogFile=classpath:db/changelog/db-changelog-master.yaml --requireForce=true dropAll
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  historydb:
    image: debezium/postgres:15-alpine
    container_name: historyDb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=history
    ports:
      - "5435:5432"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  attachment-service:
    image: attachment-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    container_name: attachment-service
    build: ./attachment-service
    depends_on:
      - attachmentdb
      - discovery-service
      - authentication-service
      - goods-service
      - order-service
      - minio
    environment:
      - SPRING_APPLICATION_JSON={"multipart":{"enabled":"true","max-file-size":"5MB","max-request-size":"5MB"}}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://attachmentdb:5432/attachments
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    command: >
      liquibase --url=jdbc:postgresql://attachmentdb:5432/attachments --username=test --password=test --driver=org.postgresql.Driver --changeLogFile=classpath:db/changelog/db-changelog-master.yaml --requireForce=true dropAll
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  attachmentdb:
    image: debezium/postgres:15-alpine
    container_name: attachmentDb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=attachments
    ports:
      - "5436:5432"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  payment-service:
    image: payment-service
    restart: unless-stopped
    ports:
      - "8087:8087"
    container_name: payment-service
    build: ./payment-service
    depends_on:
      - paymentdb
      - discovery-service
      - authentication-service
      - goods-service
      - order-service
      - kafka
      - minio
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://paymentdb:5432/payments
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    command: >
      liquibase --url=jdbc:postgresql://paymentdb:5432/payments --username=test --password=test --driver=org.postgresql.Driver --changeLogFile=classpath:db/changelog/db-changelog-master.yaml --requireForce=true dropAll
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  paymentdb:
    image: debezium/postgres:15-alpine
    container_name: paymentDb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=payments
    ports:
      - "5437:5432"
    depends_on:
      - zookeeper
      - kafka
      - kafdrop
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  createbuckets:
    container_name: createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set pironminio http://minio:9000 crmadmin 12adg~Z2gzxgnvm;
      /usr/bin/mc mb pironminio/public;
      /usr/bin/mc anonymous set public pironminio/public;
      exit 0;
      "
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  minio:
    container_name: minio
    image: bitnami/minio:latest
    environment:
      MINIO_ACCESS_KEY: "Q3AM3UQ867SPQQA43P2F"
      MINIO_SECRET_KEY: "tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
      MINIO_ROOT_USER: crmadmin
      MINIO_ROOT_PASSWORD: 12adg~Z2gzxg
    volumes:
      - ./data/storage:/bitnami/minio/data
      - ./data/minio-persistence/certs:/certs
    ports:
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 100M

  zookeeper:
    image: zookeeper:3.7.0
    restart: "no"
    container_name: zookeeper
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 100M

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 400M

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M"
    depends_on:
      - "kafka"
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 200M

  comment-service:
    image: comment-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    container_name: comment-service
    build: ./comment-service
    depends_on:
      - commentdb
      - discovery-service
      - authentication-service
      - goods-service
      - order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://commentdb:5432/comments
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    command: >
      liquibase --url=jdbc:postgresql://commentdb:5432/comments --username=test --password=test --driver=org.postgresql.Driver --changeLogFile=classpath:db/changelog/db-changelog-master.yaml --requireForce=true dropAll
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  commentdb:
    image: debezium/postgres:15-alpine
    container_name: commentDb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=comments
    ports:
      - "5438:5432"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M

  feedback-service:
    image: feedback-service
    restart: unless-stopped
    ports:
      - "8086:8086"
    container_name: feedback-service
    build: ./feedback-service
    depends_on:
      - feedbackdb
      - discovery-service
      - kafka
      - authentication-service
      - goods-service
      - order-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://feedbackdb:5432/feedbacks
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    command: >
      liquibase --url=jdbc:postgresql://feedbackdb:5432/feedbacks --username=test --password=test --driver=org.postgresql.Driver --changeLogFile=classpath:db/changelog/db-changelog-master.yaml --requireForce=true dropAll
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  feedbackdb:
    image: debezium/postgres:15-alpine
    container_name: feedbackDb
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=feedbacks
    ports:
      - "5439:5432"
    depends_on:
      - zookeeper
      - kafka
      - kafdrop
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M


