spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payments
    username: test
    password: test
    hikari:
      maximum-pool-size: 2
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  kafka:
    bootstrap-servers: 127.0.0.1:29092
    key-serializer: org.springframework.kafka.support.serializer.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.StringSerializer
    consumer:
      group-id: order
      auto-offset-reset: earliest
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db-changelog-master.yaml
    default-schema: public
    contexts: migrated
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  mail:
    properties:
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  config:
    import: 'optional:configserver:'
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  permitted:
    url:
      http://localhost:3000/**
mail:
  host: smtp.mail.ru
  port: 587
  username: denmit777@mail.ru
  password: aaCFGpWCYNSeyfg5m8Dm
  transport:
    protocol: smtp
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
  debug: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: c2Rmc2RmZHNmc2Rmc2RmZHNmc2Rmc2Rmsdffffffffsdfsdfsdf878787sd8f7s7df78sd87f78sdf87
security:
  permitted:
    urls: /payment-service/**, api/v1/receipts/**
minio:
  bucket: payment-files
  url: http://158.160.163.242:9000
  accessKey: crmadmin
  secretKey: 12adg~Z2gzxg
topic:
  order.pay
server:
  port: 8087
logging:
  level:
    -root: INFO
springdoc:
  api-docs:
    path: /payment-service/v3/api-docs
  swagger-ui:
    path: /payment-service/swagger-ui.html
openapi:
  service:
    url: http://localhost:8087
custom:
  receipt-url: http://localhost:8087/api/v1/receipts/download/

