spring:
  application:
    name: discovery-service
       
  management:  #Actuator health check
    endpoints:
      web:
        exposure:
          include: "*"
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


